version: "3"

services:
  backend:
    build: ./
    container_name: oldtimers_container
    working_dir: /oldtimers

    restart: always
    command:
      - ./commands/start_server.sh
    ports:
      - '8011:8010'

    volumes:
      - ./src:/oldtimers/src
      - static_content:/oldtimers/src/static
      - media_content:/oldtimers/src/media
    tty: true
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongo:
    container_name: mongo_db_container
    image: mongo:3-stretch
    ports:
      - '27017:27017'
    command: [ "--bind_ip_all", "--smallfiles" ]
    volumes:
      - mongo_data:/data/db
    restart: always
    env_file:
      - .env

  mongoadmin:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - '8091:8081'
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/oldtimers/src/static
      - media_content:/oldtimers/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443-443'
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }
  static_content: { }
  media_content: { }