# Generated by Django 3.2.13 on 2022-06-19 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=35, unique=True, verbose_name="username"
            ),
            preserve_default=False,
        ),
    ]
