# Generated by Django 3.2.13 on 2022-05-12 17:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=128)),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(max_length=5, verbose_name='zip code')),
                ('international_delivery', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField()),
                ('billing_address', models.CharField(default='N/A', max_length=128, verbose_name='address')),
                ('billing_city', models.CharField(max_length=64, verbose_name='city')),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('billing_zip_code', models.CharField(max_length=5, verbose_name='zip code')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=128)),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(max_length=5, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Lux Class'), (1, 'Sport Class'), (2, ' SUV Class'), (3, 'Moto'), (4, 'Race Class'), (5, ' Other')], default=5)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('production_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('condition', models.PositiveSmallIntegerField(choices=[(0, 'Excellent'), (1, 'Very Good'), (2, 'Good'), (3, 'Satisfactory'), (4, 'Poor'), (5, 'Out of order'), (6, 'Other')], default=6)),
                ('image', models.ImageField(default='default.png', upload_to='media/vehicle')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.TextField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='oldtimers.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='oldtimers.retailer')),
                ('vehicle_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='oldtimers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('invoice_line_id', models.IntegerField(db_index=True, default='N/A', primary_key=True, serialize=False)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=19)),
                ('insurance_charge', models.DecimalField(decimal_places=2, max_digits=19)),
                ('delivery_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='oldtimers.deliveryservice')),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='oldtimers.invoices')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items_price', to='oldtimers.vehicle')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items_vehicle', to='oldtimers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('rank', models.PositiveSmallIntegerField(choices=[(0, 'Chief Executive Officer'), (1, 'General Manager / Administrator'), (2, 'Sales Manager')], default=2)),
                ('email', models.EmailField(max_length=128)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='oldtimers.retailer')),
            ],
        ),
    ]
