# Generated by Django 3.2.13 on 2022-05-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryservice",
            old_name="mobile",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="retailer",
            old_name="mobile",
            new_name="phone_number",
        ),
    ]
