# Generated by Django 3.2.13 on 2022-06-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0002_auto_20220618_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="category",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "European Elite Classic"),
                    (1, "US Retro"),
                    (2, "European Legend"),
                    (3, "Fully Restored Oldtimer"),
                    (4, "US Muscle Car"),
                    (5, "Offroad Classic"),
                    (6, "Asian Legends"),
                    (7, "Rare Supercar"),
                    (8, "Deep Tuned Custom"),
                    (9, "European Racing Classics"),
                    (10, " Other"),
                ],
                default=10,
            ),
        ),
    ]
