# Generated by Django 3.2.13 on 2022-05-14 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oldtimers", "0002_auto_20220513_2101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                default="No owner. Temporary",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="vehicle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="retailer",
            field=models.ForeignKey(
                default="No retailer. Temporary",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="vehicles",
                to="oldtimers.retailer",
            ),
        ),
    ]
