# Generated by Django 3.2.13 on 2022-06-18 21:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldtimers', '0003_alter_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
