# Generated by Django 3.2.13 on 2022-05-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0005_alter_vehicle_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(db_index=True, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
