# Generated by Django 3.2.13 on 2022-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0005_retailer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users_photo/"),
        ),
    ]
