# Generated by Django 3.2.13 on 2022-06-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0006_retailer_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="vehicle",
                to="oldtimers.retailer",
            ),
        ),
    ]
