# Generated by Django 3.2.13 on 2022-05-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0007_rename_vehicle_id_offer_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryservice",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitems",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitems",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="invoices",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="invoices",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
