# Generated by Django 3.2.13 on 2022-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0007_alter_vehicle_retailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="photo",
            field=models.ImageField(blank=True, default="default.jpg", null=True, upload_to="users_photo/"),
        ),
    ]
