# Generated by Django 3.2.13 on 2022-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0008_alter_retailer_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="photo",
            field=models.ImageField(
                blank=True, default="media/users_photo/default.jpg", null=True, upload_to="users_photo/"
            ),
        ),
    ]
