# Generated by Django 3.2.13 on 2022-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0008_auto_20220514_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
