# Generated by Django 3.2.13 on 2022-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0009_retailer_service_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
    ]
