# Generated by Django 3.2.13 on 2022-05-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0010_alter_retailer_service_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="offer_price",
        ),
    ]
