# Generated by Django 3.2.13 on 2022-05-15 00:36

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0011_remove_offer_offer_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(1.0)],
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal("1"))]
            ),
        ),
    ]
