# Generated by Django 3.2.13 on 2022-05-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0012_auto_20220515_0036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="address",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="address"),
        ),
    ]
