# Generated by Django 3.2.13 on 2022-05-15 11:31

import django.core.validators
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0014_auto_20220515_1050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryservice",
            name="address",
            field=models.CharField(blank=True, max_length=128, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="city",
            field=models.CharField(blank=True, max_length=64, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="company_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="email",
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="billing_city",
            field=models.CharField(blank=True, max_length=64, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="billing_country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="address",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="address"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="retailer",
            name="city",
            field=models.CharField(blank=True, max_length=64, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="company_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="country",
            field=django_countries.fields.CountryField(blank=True, default="", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="retailer",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="zip_code",
            field=models.CharField(blank=True, max_length=5, verbose_name="zip code"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="production_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(2000),
                    django.core.validators.MinValueValidator(1900),
                ],
                verbose_name="year",
            ),
        ),
    ]
