# Generated by Django 3.2.13 on 2022-05-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0015_auto_20220515_1131"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceitems",
            old_name="delivery_charge",
            new_name="delivery_fee",
        ),
        migrations.RenameField(
            model_name="invoiceitems",
            old_name="insurance_charge",
            new_name="insurance_fee",
        ),
    ]
