# Generated by Django 3.2.13 on 2022-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oldtimers", "0016_auto_20220515_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="category",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Lux Class"),
                    (1, "Sport Class"),
                    (2, " SUV Class"),
                    (3, "Moto"),
                    (4, "Race Class"),
                    (5, " Other"),
                ],
                default=5,
            ),
        ),
    ]
